FROM ghcr.io/cirruslabs/flutter:3.41.9

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        binutils \
        ca-certificates \
        clang \
        cmake \
        curl \
        desktop-file-utils \
        file \
        libgtk-3-dev \
        libstdc++-12-dev \
        ninja-build \
        patchelf \
        pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install --yes --no-install-recommends lld llvm \
    && rm -rf /var/lib/apt/lists/*

RUN flutter precache --linux

WORKDIR /workspace
