"""Check exported AcroForms, including their logical fields and appearances.

Usage: python tools/validate_pdf_export.py FILE.pdf --characters 2
Requires pypdf. --fixture also validates the sample generated by the Dart test
and edits it to FILE.edited.pdf to check that fields remain independent.
"""

import argparse
import json
from pathlib import Path

from pypdf import PdfReader, PdfWriter


def validate(path: Path, count: int):
    reader = PdfReader(path)
    definitions = json.loads(
        (Path(__file__).resolve().parent.parent / "assets/sheet/fields.json").read_text()
    )
    fields = reader.get_fields() or {}
    expected = {
        f"character_{index}_{definition['name']}"
        for index in range(1, count + 1)
        for definition in definitions
    }
    assert len(reader.pages) == 3 * count, "Unexpected page count"
    assert set(fields) == expected, "Missing, duplicate or unexpected form fields"
    canonical = {
        reference.idnum
        for reference in reader.trailer["/Root"]["/AcroForm"]["/Fields"]
    }
    widgets = []
    for page_index, page in enumerate(reader.pages):
        definitions_on_page = {
            definition["name"]: definition
            for definition in definitions
            if definition["page"] == page_index % 3
        }
        for reference in page.get("/Annots", []):
            widget = reference.get_object()
            if widget.get("/Subtype") != "/Widget":
                continue
            widgets.append(widget)
            name = widget["/T"]
            assert reference.idnum in canonical, f"Orphan widget: {name}"
            assert name in fields and fields[name]["/V"] == widget["/V"]
            assert not widget.get("/Ff", 0) & 1, f"Read-only field: {name}"
            definition = definitions_on_page[name.split("_", 2)[2]]
            assert widget["/FT"] == ("/Tx" if definition["type"] == "text" else "/Btn")
            appearance = widget["/AP"]["/N"]
            if widget["/FT"] == "/Btn":
                assert widget["/AS"] == widget["/V"]
                assert widget["/V"] in appearance, f"Missing selected appearance: {name}"
            else:
                assert bool(widget.get("/Ff", 0) & 4096) == definition.get("multiline", False)
                assert widget["/Q"] == definition.get("align", 0)
                assert "/DA" in widget, f"Missing font for editing: {name}"
                assert appearance.get("/Subtype") == "/Form"
                if widget["/V"]:
                    assert appearance.get_data(), f"Empty appearance: {name}"
    assert len(widgets) == len(expected), "Unexpected widget count"
    return reader, fields


def check_fixture(path: Path, reader, fields):
    expected_values = {
        "character_1_CharacterName": "Éowyn – Guardiana",
        "character_1_CharacterName 2": "Éowyn – Guardiana",
        "character_1_STR": "18",
        "character_1_ClassLevel": "Guerriera 5",
        "character_1_PersonalityTraits ": "Coraggiosa e leale.\nDifende la sua compagnia.",
        "character_1_Check Box 11": "/Yes",
        "character_1_Check Box 23": "/Expertise",
        "character_1_Check Box 24": "/Yes",
        "character_2_CharacterName": "Thorin",
        "character_2_STR": "12",
        "character_2_Check Box 23": "/Yes",
        "character_2_Check Box 24": "/Off",
    }
    for name, value in expected_values.items():
        assert fields[name]["/V"] == value, f"Value mismatch: {name}"
    assert len(reader.pages[1].images) == 2, "Missing portrait"
    notes = [
        annotation.get_object()["/Contents"]
        for annotation in reader.pages[0]["/Annots"]
        if annotation.get_object()["/Subtype"] == "/Text"
    ]
    assert notes == ["Bonus temporaneo: +2 durante la furia."]

    writer = PdfWriter()
    writer.clone_document_from_reader(reader)
    writer.update_page_form_field_values(
        None,
        {"character_1_CharacterName": "Nuovo eroe: àèìòù", "character_1_STR": "20", "character_1_Check Box 23": "/Off"},
        auto_regenerate=False,
    )
    edited_path = path.with_suffix(".edited.pdf")
    writer.write(edited_path)
    _, edited = validate(edited_path, 2)
    assert edited["character_1_CharacterName"]["/V"] == "Nuovo eroe: àèìòù"
    assert edited["character_1_STR"]["/V"] == "20"
    assert edited["character_1_Check Box 23"]["/V"] == "/Off"
    assert edited["character_2_STR"]["/V"] == "12"
    assert edited["character_2_Check Box 23"]["/V"] == "/Yes"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pdf", type=Path)
    parser.add_argument("--characters", required=True, type=int)
    parser.add_argument("--fixture", action="store_true")
    args = parser.parse_args()
    reader, fields = validate(args.pdf, args.characters)
    if args.fixture:
        check_fixture(args.pdf, reader, fields)
    print(f"OK: {len(reader.pages)} pages, {len(fields)} editable fields, valid values and appearances")
